server {
  listen 80;
  server_name qfx-finance.com www.qfx-finance.com;
  location / { proxy_pass http://localhost:3000; }
  location /admin { proxy_pass http://localhost:3001; }
  location /api { proxy_pass http://localhost:5000; }
}
